### ISSUE TITLE
The cause of mismatch for model params

### ISSUE THREAD

**Issue by azraelkuan** [mindslab-ai/univnet#2]
for your note:

> Our UnivNet generator has smaller number of parameters (c32: 5.11M, c16: 1.42M) than the paper (c32: 14.89M, c16: 4.00M). So far, we have not encountered any issues from using a smaller model size. If run into any problem, please report it as an issue.

it should be a mistake in your code:
https://github.com/mindslab-ai/univnet/blob/df77c9a37f71e3d6be1b504e16abaf99ce131de3/model/lvcnet.py#L110

the default value should be **3**, but u set to **1** in the code.

**Comment by wookladin** [comment]
Thanks for reporting the problem!
We really appreciate it.
As many open sources do, we want to invite you as a contributor to this repository.
To become a contributor, you should fork this repository, edit it, and send us a pull request.
We will accept your pull request when training of our modified model is done.
If you don't want to be a contributor, you don't have to do this.

Thanks again.

**Comment by azraelkuan** [comment]
@wookladin i have created a pr, so close this.
